
FROM node:18-alpine AS deps

WORKDIR /app

COPY ./client/package.json ./client/package-lock.json ./

RUN npm ci

FROM node:18-alpine AS dev

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package-lock.json ./package-lock.json

COPY ./client/ .
