FROM oven/bun:latest

WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./tsconfig.json ./tsconfig.json

RUN bun install --production

COPY ./src ./src

CMD ["bun", "src/index.ts"]
