FROM node:latest

WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN yes | npm install -g npm
#DONT FORGET TO CHANGE FLAG BACK TO PROD
RUN yes | npm install --production=false
